
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import { v4 as uuidv4 } from 'uuid';
import User from '../src/models/User.js';

// Setup environment
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../.env') });

const migrateDualWallets = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('✅ Connected to MongoDB');

        const users = await User.find({});
        console.log(`Found ${users.length} users. Checking for ConvergeX Wallets...`);

        let updatedCount = 0;

        for (const user of users) {
            let needsUpdate = false;

            // Check if convergeXWallet exists and has address
            if (!user.convergeXWallet || !user.convergeXWallet.address) {
                user.convergeXWallet = {
                    address: `cx_${uuidv4().replace(/-/g, '').substring(0, 20)}`,
                    balance: {
                        usdc: user.cryptoBalance?.usdc || 1000, // Preserve old if exists
                        dai: user.cryptoBalance?.dai || 500,
                        eth: user.cryptoBalance?.eth || 1
                    },
                    createdAt: new Date(),
                    isActive: true
                };
                console.log(`   + Created ConvergeX Wallet for ${user.email}: ${user.convergeXWallet.address}`);
                needsUpdate = true;
            }

            // Initialize metamaskWallet if missing
            if (!user.metamaskWallet) {
                user.metamaskWallet = {
                    address: "",
                    isConnected: false
                };
                needsUpdate = true;
            }

            // Initialize transactions array
            if (!user.walletTransactions) {
                user.walletTransactions = [];
                needsUpdate = true;
            }

            // Force save to persist defaults generated by Mongoose schema
            await user.save();
            updatedCount++;
        }

        console.log(`\n🎉 Migration Complete. Updated ${updatedCount} users.`);
        process.exit(0);
    } catch (error) {
        console.error('❌ Error:', error);
        process.exit(1);
    }
};

migrateDualWallets();
